src/main/java/HB_CAPE_MAK/hb_cape_makindu/entity/Genre.java
package HB_CAPE_MAK.hb_cape_makindu.entity;

import HB_CAPE_MAK.hb_cape_makindu.entity.interfaces.NomenclatureInterface;
import HB_CAPE_MAK.hb_cape_makindu.entity.interfaces.SluggerInterface;
import HB_CAPE_MAK.hb_cape_makindu.json_views.JsonViews;
import com.fasterxml.jackson.annotation.JsonView;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Genre implements SluggerInterface,
        NomenclatureInterface {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonView(JsonViews.GenrePrivateView.class)
    private Long id;

    @Column(nullable = false, unique = true)
    @JsonView(JsonViews.GenrePublicView.class)
    private String name;

    @JsonView(JsonViews.GenrePublicView.class)
    private String slug;

    @OneToMany(mappedBy = "genre")
    @JsonView(JsonViews.GenrePublicView.class)
    private List<Game> games = new ArrayList<>();

    @Override
    public String getField() {
        return name;
    }
}

src/main/java/HB_CAPE_MAK/hb_cape_makindu/entity/User.java
package HB_CAPE_MAK.hb_cape_makindu.entity;

import HB_CAPE_MAK.hb_cape_makindu.json_views.JsonViews;
import com.fasterxml.jackson.annotation.JsonView;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Inheritance (strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn (name = "type", discriminatorType = DiscriminatorType.STRING)
public abstract class User  implements UserDetails {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonView(JsonViews.UserPrivateView.class)
    protected Long id;

    @Column(nullable = false)
    @JsonView(JsonViews.UserPublicView.class)
    protected String pseudo;

    @Column(nullable = false)
    @JsonView(JsonViews.UserPrivateView.class)
    protected String email;

    @Column(nullable = false)
    @JsonView(JsonViews.UserPrivateView.class)
    protected String pwd;

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return null;
    }

    @Override
    public String getPassword() {
        return pwd;
    }

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }

    public boolean isModerator() {
        return this instanceof Moderator;
    }

}

src/main/java/HB_CAPE_MAK/hb_cape_makindu/controller/AboutController.java
package HB_CAPE_MAK.hb_cape_makindu.controller;

import HB_CAPE_MAK.hb_cape_makindu.DTO.ReviewDTO;
import HB_CAPE_MAK.hb_cape_makindu.mapping.UrlRoute;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import java.security.Principal;

@Controller
@RequestMapping(name = "AppAbout")
@AllArgsConstructor
public class AboutController {
    @GetMapping(path = UrlRoute.URL_ABOUT)
    public ModelAndView about(

            ModelAndView mav,
            Principal principal
    ) {
        if (principal == null) {
            mav.setViewName("redirect:/login");
            return mav;
        }
        {
            mav.setViewName("about");
            return mav;
        }

}
}

src/main/java/HB_CAPE_MAK/hb_cape_makindu/controller/GenreController.java
package HB_CAPE_MAK.hb_cape_makindu.controller;

import HB_CAPE_MAK.hb_cape_makindu.DTO.GameDTO;
import HB_CAPE_MAK.hb_cape_makindu.DTO.GenreDTO;
import HB_CAPE_MAK.hb_cape_makindu.mapping.UrlRoute;
import HB_CAPE_MAK.hb_cape_makindu.service.*;
import HB_CAPE_MAK.hb_cape_makindu.utils.FlashMessageBuilder;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.security.Principal;

@Controller
@RequestMapping(name = "AppGenre")
@AllArgsConstructor
public class GenreController {
    GenreServiceImpl genreService;
    GameServiceImpl gameService;
    ClassificationServiceImpl classificationService;
    PublisherServiceImpl publisherService;
    BusinessModelServiceImpl businessModelService;
    PlatformServiceImpl platformService;
    private FlashMessageBuilder flashMessageBuilder;

    @GetMapping(path = UrlRoute.URL_GENRE)
    public ModelAndView genre(
            ModelAndView mav,
            Principal principal
    ) throws Throwable {
        if (principal == null) {
            mav.setViewName("redirect:/login");
            return mav;
        }
        {
            mav.setViewName("genre");
            mav.addObject("genreDto", new GenreDTO());
            mav.addObject("gameDto", new GameDTO());
            mav.addObject("AllGenre", genreService.findAll());
            mav.addObject("genres", genreService.findAllSorted());
            mav.addObject("classifications", classificationService.findAllSorted());
            mav.addObject("businessModels", businessModelService.findAllSorted());
            mav.addObject("publishers", publisherService.findAllSorted());
            mav.addObject("platforms", platformService.findAllSorted());

            return mav;
        }
    }


    @PostMapping(UrlRoute.URL_GENRE)
    public ModelAndView create(
            ModelAndView mav,
            @ModelAttribute("gameDto") GameDTO gameDTO,
            BindingResult bindingResult,
            RedirectAttributes redirectAttributes,
            Principal principal
    ) {
        if (bindingResult.hasErrors()) {
            mav.setViewName("genre");
            return mav;
        }

        redirectAttributes.addFlashAttribute(
                "flashMessage",
                flashMessageBuilder.createSuccessFlashMessage("Jeu créé avec succès !")
        );
        mav.setViewName("redirect:" + UrlRoute.URL_GAME + "/" + gameService.create(gameDTO, principal.getName()).getSlug());
        return mav;
    }


}

src/main/webapp/WEB-INF/jsp/about.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="tag.jsp" %>
<c:set var="title" scope="request" value="CapEntre"/>
<jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/base.jsp"/>


<section class=" container top_about_wallpaper">

</section>

<section class="container flex-column gap-4 col-8 justify-content-around align-items-center storytell">
    <div class="container">
        <h2 class="mt-5 mb-3 genese">Notre Génèse</h2>
        <p>En 2022, une pluie de météorites a inspiré la création d'Infinity Gaming, une plateforme innovante dédiée au
            dépôt d'avis dans le domaine du jeu vidéo.</p>
        <h6 class="mt-5 mb-3">Une Vision de Transparence : Création de la Plateforme</h6>
        <p>Infinity Gaming a été conçu pour offrir un espace où les joueurs peuvent partager honnêtement leurs
            expériences et opinions sur les jeux vidéo <br> Améliorant ainsi la qualité et l'intégrité du secteur.</p>
    </div>


    <hr>

    <div class="container">
        <h4 class="mt-5 mb-3">Développement et Lancement : L'Émergence d'un Nouveau Standard</h4>
        <p>Avec un investissement initial de 20 000 $, l'équipe a développé un site web ergonomique. <br> Favorisant une
            interaction facile et fiable pour les utilisateurs souhaitant déposer ou consulter des avis.</p>

    </div>
    <hr>

    <div class="container">
        <h4 class="mt-5 mb-3">Premiers Pas et Réception : Un Accueil Chaleureux</h4>
        <p>Le lancement d'Infinity Gaming a été salué par la communauté, attirant plus de 5 000 utilisateurs dans les
            deux premières semaines. <br> Prouvant l'intérêt grandissant pour une plateforme d'avis transparente et
            fiable.</p>
        <h6 class="mt-5 mb-3">Croissance et Évolution : Une Référence dans le Milieu</h6>
        <p>En seulement six mois, Infinity Gaming est devenu un acteur clé, avec plus de 50 000 avis déposés, jouant un
            rôle crucial dans les décisions d'achat des joueurs du monde entier.</p>
    </div>

    <div class="container">
        <h4 class="mt-5 mb-3">Impact et Avenir : Redéfinir les Avis dans le Jeu Vidéo</h4>
        <p>Infinity Gaming a non seulement transformé la façon dont les avis sont partagés et perçus dans l'industrie du
            jeu vidéo, mais a également établi un nouveau standard de transparence et d'intégrité pour l'avenir.</p>
    </div>

</section>


<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/jsp/base.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="tag.jsp" %>
<%
    Object title = request.getAttribute("title");
    if (title == null) {
        title = "InfinityGaming";
    }
    request.setAttribute("title", title);
%>

<html lang="fr">
<head>

    <title>${title}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<%-- CSS--%>
    <link href="${contextPath}/css/main.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
    <link href="${contextPath}/css/component/pagination.css" rel="stylesheet">
<%-- JAVASCRIPT--%>
    <script type="text/javascript" src="${contextPath}/js/init-sortable.js"></script>
    <script type="text/javascript" src="${contextPath}/js/hide-form.js"></script>
    <script type="text/javascript" src="${contextPath}/js/alert.js"></script>
    <script type="text/javascript" src="${contextPath}/js/multiple-select.js"></script>

<%-- LOGO --%>
    <link rel="icon" type="image/png" href="${contextPath}/media/Logo-removebg-preview.png"/>
</head>
<body>


<%-- Navbarici : SI NECESSAIRE --%>
<nav class="navbar navbar-expand-lg d-flex align-items-center justify-content-around col-12 fixed-top">
    <a href="/" class="logo">
        <img src="${contextPath}/media/Logo-removebg-preview.png" width="130vw" height="120vh">
    </a>

    <security:authorize access="isAuthenticated()">
    <div class="collapse navbar-collapse d-flex align-items-center justify-content-between " id="navbarSupportedContent">
        <ul class="navbar-nav d-flex align-items-center justify-content-around text-white gap-5">
            <li class="nav-item">
                <a class="nav-link menu-link" href="${UrlRoute.URL_GENRE}">Genre</a>
            </li>
            <li class="nav-item">
                <a class="nav-link menu-link" href="/#top4">Top</a>
            </li>
            <security:authorize access="hasRole('ROLE_MODERATOR')">
            <li class="nav-item">
                <a class=" menu-link admin_access" href="${UrlRoute.URL_GENRE}#add_game">Ajouter un Jeu</a>
            </li>
            </security:authorize>
        </ul>

        <div class="welcome_message d-inline-flex justify-content-center align-items-center">
            <span class="pe-2">Bonjour <span class="subspan"><security:authentication property="name"/></span></span>
            <security:authorize access="hasRole('GAMER')">
            <a href="/"><i class="fa-regular fa-user security-icon"></i></a>
            </security:authorize>
            <security:authorize access="hasRole('MODERATOR')">
            <a href="/"><i class="fa-solid fa-user-shield security-icon"></i></a></security:authorize>

            <span class="pe-2"> | </span>
            <form method="POST" action="${UrlRoute.URL_LOGOUT}" autocomplete="off">
                <button type="submit" tabindex="3" class="btn btn-link">
                    <i class="fa-solid fa-arrow-right-from-bracket security-icon"></i>
                </button>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
            </form>
        </div>
    </div>
    </security:authorize>
</nav>

src/main/webapp/WEB-INF/jsp/footer.jsp
<%--Footer from : https://mdbootstrap.com/docs/standard/navigation/footer/--%>
<%@ page contentType="text/html;charset=UTF-8" %>
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Parlez en aussi sur nos réseaux sociaux</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        <i class="fas fa-gem me-3"></i>InfinityGaming
                    </h6>
                    <p>
                        Parce que la communauté compte, vos avis compte. Retrouvez les commentaires les plus pertinents de vos jeux préférés. Les notes les plus impartiales. Créez les jeux, faites et défaites les.
                    </p>
                </div>
                <!-- Grid column -->


                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Useful links
                    </h6>
                    <p>
                        <a href="/#all_comment" class="text-reset">Les avis</a>
                    </p>
                    <p>
                        <a href="#/" class="text-reset">Votre compte</a>
                    </p>
                    <p>
                        <a href="${UrlRoute.URL_ABOUT}" class="text-reset">À propos</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p><a href="https://maps.app.goo.gl/BL6z11APviYpv51o7"><i class="fas fa-home me-3"></i> Jamestown, Saint-Hélène</a></p>
                    <p><a href="mailto:InfinityGame@nft.com">
                        <i class="fas fa-envelope me-3"></i>
                        InfinityGame@nft.com
                    </a></p>
                    <p itemprop="telephone"> <a href="tel:+290556585822"><i class="fas fa-phone me-3"></i> +290 5 56 58 58 22 </a> </p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Copyright
        <a class="text-reset fw-bold" href="/">InfinityGaming.com</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
    </body>
</html>

src/main/webapp/WEB-INF/jsp/genre.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="tag.jsp" %>
<c:set var="title" scope="request" value="CapEntre"/>
<jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/base.jsp"/>


<section class="top_wallpaper genrewlp">
</section>

<section class="container flex-column justify-content-around gap-2 col-12 flex-wrap genresection">
    <h2 class="pb-3" id="add_game">Nos jeux par genre  <c:if test="${userLogged.moderator}">
        <a title="Ajouter un commentaire" data-hide-show-button="formGame">
        <i class="fa-solid fa-plus"></i>
        </a>
    </c:if>
    </h2>


<c:if test="${userLogged.moderator}" >
    <f:form method="POST" modelAttribute="gameDto" class="col-lg-8 col-md-12 col-sm-12 mx-auto" data-hide-show-container="formGame">
        <div class="row mb-3">
            <div class="col-md-8 col-sm-12">
                <f:label class="col-form-label" path="name">Nom</f:label>
                <f:input type="text" path="name"
                         class="form-control"
                         placeholder="Nom"
                         autofocus="true"/>
                <f:errors path="name" cssClass="invalid-feedback"/>
            </div>
            <div class="col-md-4 col-sm-12">
                <f:label class="col-form-label" path="releaseDate">Date de sortie</f:label>
                <f:input type="date" path="releaseDate"
                         class="form-control"
                         autofocus="true"/>
                <f:errors path="releaseDate" cssClass="invalid-feedback"/>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-4 col-sm-12">
                <f:label class="col-form-label" path="genre">
                    Genre
                </f:label>
                <f:select path="genre"
                          items="${genres}"
                          cssClass="form-select"
                          itemLabel="name"
                >
                </f:select>
                <f:errors path="genre" cssClass="invalid-feedback"/>
            </div>
            <div class="col-md-4 col-sm-12">
                <f:label class="col-form-label" path="classification">
                    Classification
                </f:label>
                <f:select path="classification"
                          items="${classifications}"
                          cssClass="form-select"
                          itemLabel="name"
                >
                </f:select>
                <f:errors path="classification" cssClass="invalid-feedback"/>
            </div>
            <div class="col-md-4 col-sm-12">
                <f:label class="col-form-label" path="businessModel">
                    Modèle économique
                </f:label>
                <f:select path="businessModel"
                          items="${businessModels}"
                          cssClass="form-select"
                          itemLabel="name"
                >
                </f:select>
                <f:errors path="businessModel" cssClass="invalid-feedback"/>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6 col-sm-12">
                <f:label class="col-form-label" path="publisher">
                    Editeur
                </f:label>
                <f:select path="publisher"
                          items="${publishers}"
                          cssClass="form-select"
                          itemLabel="name"
                >
                </f:select>
                <f:errors path="publisher" cssClass="invalid-feedback"/>
            </div>
            <div class="col-md-6 col-sm-12">
                <f:label class="col-form-label" path="platforms">
                    Plateformes
                </f:label>
                <input class="form-control" data-multiple-select-input="platforms"/>
                <f:select path="platforms"
                          items="${platforms}"
                          cssClass="form-select"
                          itemLabel="name"
                          data-multiple-select="platforms"
                >
                </f:select>
                <f:errors path="platforms" cssClass="invalid-feedback"/>
            </div>
        </div>
        <div class="col-12 mb-3">
            <f:label class="col-form-label" path="description">Description</f:label>
            <f:textarea type="text" path="description"
                        class="form-control"
                        placeholder="Description"
                        autofocus="true"/>
            <f:errors path="description" cssClass="invalid-feedback"/>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">
            Valider
        </button>
    </f:form>
</c:if>






    <div class="container flex-column">
        <c:forEach items="${AllGenre}" var="genre">

            <c:if test="${genre.games.size()!=0}">
                <h3 class="pt-3 pb-2">${genre.name.toUpperCase()}</h3>
            </c:if>


            <c:forEach items="${genre.games}" var="game">
                <a href="${UrlRoute.URL_GAME}/${game.slug}" class="card-link">
                    <div class="card container d-inline-flex genresection-card mb-5"
                         style="background-image:url(${game.image})">
                    </div>
                </a>
            </c:forEach>

        </c:forEach>
    </div>
    <hr>


</section>

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="tag.jsp" %>
<c:set var="title" scope="request" value="CapEntre"/>
<jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/base.jsp"/>


<section class="top_wallpaper">
</section>

<section class="container d-flex justify-content-evenly col-md-12 gap-4 flex-wrap mb-5 sibling-fade">

    <h2 id="all_comment">Tous les commentaires</h2>
    <%--  FILTRES & DOWNLOAD --%>
    <div class="container d-flex col-md-12 gap-2 filter">
        <c:set var="label" scope="request" value="Date"/>
        <c:set var="sortable" value="createdAt"/>
        <%@ include file="component/sortable.jsp" %>

        <c:set var="label" scope="request" value="Note"/>
        <c:set var="sortable" value="rating"/>
        <%@ include file="component/sortable.jsp" %>

        <c:set var="label" scope="request" value="Jeu"/>
        <c:set var="sortable" value="game"/>
        <%@ include file="component/sortable.jsp" %>

        <c:set var="label" scope="request" value="Joueur"/>
        <c:set var="sortable" value="gamer"/>
        <%@ include file="component/sortable.jsp" %>

        <%@ include file="component/filter-reset.jsp" %>

        <security:authorize access="hasRole('MODERATOR')">
            <a href="${UrlRoute.URL_EXPORT}" class="excel">
                <i class="fa-regular fa-file-excel"></i>
                Export Excel
            </a>
        </security:authorize>

        <%-- MODERATED FILTER --%>
        <security:authorize access="hasRole('MODERATOR')">
            <div class="sort-filter mt-4 me-3">
                <select class="form-select sortable-select">
                    <option value="all" data-filter-url="${currentUrl}">
                        Tous les commentaires
                    </option>
                    <option value="sort=moderator,desc"
                            data-filter-url="${jspUtils.generateUrlFrom(currentUrl, currentQuery, "sort=moderator,desc")}"
                    >
                        Modérés
                    </option>
                    <option value="sort=moderator,asc"
                            data-filter-url="${jspUtils.generateUrlFrom(currentUrl, currentQuery, "sort=moderator,asc")}"
                    >
                        À modérer
                    </option>
                </select>
            </div>
        </security:authorize>
    </div>
</section>

<section class="container d-flex align-content-around flex-wrap justify-content-around gap-5 mt-5 mb-5 card-section">
    <c:forEach items="${pageReviews.content}" var="review">
        <div class="container card text-center slide_diagonal" title="${review.game.name}">
            <a href="${UrlRoute.URL_REVIEW}/${review.id}">
                <div class="card-body">
                    <div class="d-inline">
                    <h5 class="card-title flex-lg-row">${jspUtils.excerpt(review.game.name, 12)}</h5>
                    <p class="${jspUtils.getCssClass(review.rating)} pastille" title="${review.rating}"></p>
                    </div>


                    <c:if test="${not empty review.moderator}">
                        <cite title="A modérer" class="modstatus">Modéré par ${review.moderator.pseudo}
                            le ${dateUtils.getDateFormat(review.moderatedAt, "dd/MM/yyyy")}</cite>
                    </c:if>

                    <c:if test="${empty review.moderator}">
                        <cite title="A modérer" class="modstatus">En attente de moderation</cite>⌛
                    </c:if>
                </div>
                <blockquote class="blockquote d-column-flex align-items-center justify-content-center">
                    <p>${jspUtils.excerpt(review.description, 55)}</p>
                </blockquote>
            </a>
            <p class="text-muted">Par ${review.gamer.pseudo}
                le ${dateUtils.getDateFormat(review.createdAt, "dd/MM/yyyy")}</p>
            <div class="container d-inline">
                <c:if test="${empty review.moderator}">
                    <c:if test="${userLogged.moderator}">
                        <a class="btn btn-link fa fa-check " href="${UrlRoute.URL_REVIEW_MODERATE}/${review.id}/1"
                           title="Accepter">
                        </a>
                        /
                        <a class="btn btn-link fa fa-xmark " href="${UrlRoute.URL_REVIEW_MODERATE}/${review.id}/0"
                           title="Refuser">
                        </a>
                    </c:if>
                </c:if>
            </div>
        </div>

    </c:forEach>
<%--    <jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/component/pagination.jsp"/>--%>
    <c:set var="page" scope="request" value="${pageReviews}"/>
    <%@ include file="component/pagination.jsp" %>
</section>
<%--    <jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/component/pagination.jsp"/>--%>



<hr>

<h3 class="container top4header" id="top4">Les plus commentés de la semaine</h3>
<%--TOP 4 SECTION--%>
<section class="container d-flex justify-content-around mt-4 gap-5 flex-wrap top4section">
    <c:forEach items="${Top4TrendGames}" var="game">
        <a href="${UrlRoute.URL_GAME}/${game.slug}" class="card-link">
            <div class="card my-4 top4bg" style="background-image:url(${game.image})">
            </div>
            <div class="card-body d-inline-flex justify-content-center">
                <p class="card-text">${game.name}</p>
            </div>
        </a>
    </c:forEach>
</section>

<%@ include file="footer.jsp" %>

src/main/webapp/WEB-INF/jsp/upload-image.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="tag.jsp" %>
<c:set var="title" scope="request" value="Téléverser une image"/>
<jsp:include flush="true" page="${contextPath}/WEB-INF/jsp/base.jsp"/>

<div class="container mt-5">
    <h1>Téléverser une image pour un jeu</h1>

    <c:set var="label" scope="request" value=""/>
    <c:set var="urlAction" value="${currentUrl}"/>
    <%@ include file="component/form-upload.jsp" %>

</div>

<%@ include file="footer.jsp" %>